---

- name: configure local dns resolver
  ansible.builtin.template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0644
    force: yes
  when: "'dns' not in group_names" # don't want to set this on the dns servers, it will break things