---

- name: restart sshd
  service:
    name: sshd
    state: restarted

# handlers file for ntp

- name: restart ntp
  service:
    name: ntp
    state: restarted

- name: restart clamav
  ansible.builtin.systemd:
    name: ${item}
    state: restarted
    enabled: yes
  with_items:
    - clamav-daemon
    - clamav-freshclam