---

- name: restart sshd
  service:
    name: sshd
    state: restarted

# handlers file for ntp

- name: restart ntp
  service:
    name: ntp
    state: restarted
    
# handler for metricbeat

- name: restart metricbeat
  service:
    name: metricbeat
    state: restarted
    

